// Mock data for the ERP system
import type { User, Customer, Product, Supplier, SalesOrder, PurchaseOrder, Warehouse } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    username: "admin",
    password: "admin123",
    name: "Abebe Admin",
    email: "abebe@etgcompany.et",
    role: "admin",
    active: true,
  },
  {
    id: "2",
    username: "manager",
    password: "manager123",
    name: "Kebede Manager",
    email: "kebede@etgcompany.et",
    role: "manager",
    active: true,
  },
  {
    id: "3",
    username: "sales",
    password: "sales123",
    name: "Mulu Sales",
    email: "mulu@etgcompany.et",
    role: "sales",
    active: true,
  },
  {
    id: "4",
    username: "procurement",
    password: "procurement123",
    name: "Tekle Procurement",
    email: "tekle@etgcompany.et",
    role: "procurement",
    active: true,
  },
  {
    id: "5",
    username: "warehouse",
    password: "warehouse123",
    name: "Berhanu Warehouse",
    email: "berhanu@etgcompany.et",
    role: "warehouse",
    active: true,
  },
  {
    id: "6",
    username: "finance",
    password: "finance123",
    name: "Aster Finance",
    email: "aster@etgcompany.et",
    role: "finance",
    active: true,
  },
]

export const mockCustomers: Customer[] = [
  {
    id: "C001",
    name: "Addis Ababa Traders PLC",
    email: "contact@aatriaders.et",
    phone: "+251-11-123-4567",
    country: "Ethiopia",
    creditLimit: 50000,
    createdAt: "2024-01-15",
  },
  {
    id: "C002",
    name: "Dire Dawa Importers Ltd",
    email: "info@ddimporters.et",
    phone: "+251-33-123-4567",
    country: "Ethiopia",
    creditLimit: 75000,
    createdAt: "2024-02-20",
  },
  {
    id: "C003",
    name: "Mekelle Exports Association",
    email: "sales@mekellexport.et",
    phone: "+251-34-123-4567",
    country: "Ethiopia",
    creditLimit: 100000,
    createdAt: "2024-03-10",
  },
  {
    id: "C004",
    name: "Jimma Coffee Traders",
    email: "orders@jimmacoffee.et",
    phone: "+251-47-123-4567",
    country: "Ethiopia",
    creditLimit: 60000,
    createdAt: "2024-04-05",
  },
]

export const mockProducts: Product[] = [
  {
    id: "P001",
    code: "COF-001",
    name: "Premium Ethiopian Coffee Beans (Bag of 60kg)",
    category: "Agricultural Products",
    unit: "Bag",
    costPrice: 1500,
    salePrice: 2500,
    currentStock: 200,
    reorderLevel: 50,
  },
  {
    id: "P002",
    code: "SES-001",
    name: "White Sesame Seeds (Bag of 50kg)",
    category: "Agricultural Products",
    unit: "Bag",
    costPrice: 2000,
    salePrice: 3200,
    currentStock: 150,
    reorderLevel: 30,
  },
  {
    id: "P003",
    code: "HND-001",
    name: "Handmade Leather Bags (Set of 10)",
    category: "Handicrafts",
    unit: "Set",
    costPrice: 3000,
    salePrice: 5000,
    currentStock: 80,
    reorderLevel: 20,
  },
  {
    id: "P004",
    code: "JWL-001",
    name: "Traditional Silver Jewelry (Box of 20)",
    category: "Handicrafts",
    unit: "Box",
    costPrice: 4000,
    salePrice: 7000,
    currentStock: 60,
    reorderLevel: 15,
  },
  {
    id: "P005",
    code: "SPC-001",
    name: "Ethiopian Spices Collection (Pack of 20)",
    category: "Food Products",
    unit: "Pack",
    costPrice: 1200,
    salePrice: 2200,
    currentStock: 120,
    reorderLevel: 30,
  },
]

export const mockSuppliers: Supplier[] = [
  {
    id: "S001",
    name: "Oromia Coffee Farmers Cooperative",
    email: "sales@oromiacoop.et",
    phone: "+251-11-234-5678",
    country: "Ethiopia",
    paymentTerms: "Net 30",
    createdAt: "2023-06-15",
  },
  {
    id: "S002",
    name: "Jimma Agricultural Products Ltd",
    email: "wholesale@jimmagri.et",
    phone: "+251-47-234-5678",
    country: "Ethiopia",
    paymentTerms: "Net 45",
    createdAt: "2023-07-20",
  },
  {
    id: "S003",
    name: "Addis Ababa Handicrafts Association",
    email: "orders@aahandicrafts.et",
    phone: "+251-11-345-6789",
    country: "Ethiopia",
    paymentTerms: "Net 30",
    createdAt: "2023-08-10",
  },
]

export const mockSalesOrders: SalesOrder[] = [
  {
    id: "SO001",
    orderNumber: "SO-2024-001",
    customerId: "C001",
    customerName: "Addis Ababa Traders PLC",
    orderDate: "2024-11-01",
    deliveryDate: "2024-11-15",
    status: "completed",
    items: [
      {
        productId: "P001",
        productName: "Premium Ethiopian Coffee Beans (Bag of 60kg)",
        quantity: 20,
        unitPrice: 2500,
        costPrice: 1500,
        total: 50000,
      },
    ],
    subtotal: 50000,
    tax: 5000,
    total: 55000,
    profit: 20000,
    createdBy: "Mulu Sales",
  },
  {
    id: "SO002",
    orderNumber: "SO-2024-002",
    customerId: "C002",
    customerName: "Dire Dawa Importers Ltd",
    orderDate: "2024-11-05",
    deliveryDate: "2024-11-20",
    status: "shipped",
    items: [
      {
        productId: "P003",
        productName: "Handmade Leather Bags (Set of 10)",
        quantity: 15,
        unitPrice: 5000,
        costPrice: 3000,
        total: 75000,
      },
    ],
    subtotal: 75000,
    tax: 7500,
    total: 82500,
    profit: 30000,
    createdBy: "Mulu Sales",
  },
  {
    id: "SO003",
    orderNumber: "SO-2024-003",
    customerId: "C003",
    customerName: "Mekelle Exports Association",
    orderDate: "2024-12-01",
    deliveryDate: "2024-12-15",
    status: "approved",
    items: [
      {
        productId: "P002",
        productName: "White Sesame Seeds (Bag of 50kg)",
        quantity: 30,
        unitPrice: 3200,
        costPrice: 2000,
        total: 96000,
      },
      {
        productId: "P004",
        productName: "Traditional Silver Jewelry (Box of 20)",
        quantity: 10,
        unitPrice: 7000,
        costPrice: 4000,
        total: 70000,
      },
    ],
    subtotal: 166000,
    tax: 16600,
    total: 182600,
    profit: 78000,
    createdBy: "Mulu Sales",
  },
  {
    id: "SO004",
    orderNumber: "SO-2024-004",
    customerId: "C004",
    customerName: "Jimma Coffee Traders",
    orderDate: "2024-12-10",
    deliveryDate: "2024-12-25",
    status: "draft",
    items: [
      {
        productId: "P005",
        productName: "Ethiopian Spices Collection (Pack of 20)",
        quantity: 25,
        unitPrice: 2200,
        costPrice: 1200,
        total: 55000,
      },
    ],
    subtotal: 55000,
    tax: 5500,
    total: 60500,
    profit: 25000,
    createdBy: "Mulu Sales",
  },
]

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: "PO001",
    poNumber: "PO-2024-001",
    supplierId: "S001",
    supplierName: "Oromia Coffee Farmers Cooperative",
    orderDate: "2024-10-15",
    expectedDate: "2024-11-15",
    status: "completed",
    items: [
      {
        productId: "P001",
        productName: "Premium Ethiopian Coffee Beans (Bag of 60kg)",
        quantity: 250,
        unitPrice: 1500,
        total: 375000,
      },
    ],
    total: 375000,
    createdBy: "Tekle Procurement",
  },
  {
    id: "PO002",
    poNumber: "PO-2024-002",
    supplierId: "S002",
    supplierName: "Jimma Agricultural Products Ltd",
    orderDate: "2024-11-01",
    expectedDate: "2024-12-01",
    status: "received",
    items: [
      {
        productId: "P002",
        productName: "White Sesame Seeds (Bag of 50kg)",
        quantity: 200,
        unitPrice: 2000,
        total: 400000,
      },
    ],
    total: 400000,
    createdBy: "Tekle Procurement",
  },
  {
    id: "PO003",
    poNumber: "PO-2024-003",
    supplierId: "S003",
    supplierName: "Addis Ababa Handicrafts Association",
    orderDate: "2024-12-01",
    expectedDate: "2024-12-20",
    status: "ordered",
    items: [
      {
        productId: "P003",
        productName: "Handmade Leather Bags (Set of 10)",
        quantity: 100,
        unitPrice: 3000,
        total: 300000,
      },
      {
        productId: "P004",
        productName: "Traditional Silver Jewelry (Box of 20)",
        quantity: 80,
        unitPrice: 4000,
        total: 320000,
      },
    ],
    total: 620000,
    createdBy: "Tekle Procurement",
  },
]

export const mockWarehouses: Warehouse[] = [
  {
    id: "W001",
    name: "Addis Ababa Main Warehouse",
    location: "Bole Industrial Area",
    capacity: 10000,
  },
  {
    id: "W002",
    name: "Djibouti Port Hub",
    location: "Djibouti Port",
    capacity: 5000,
  },
]
