// Mock data for the ERP system
import type { User, Customer, Product, Supplier, SalesOrder, PurchaseOrder, Warehouse } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    username: "admin",
    password: "admin123",
    name: "Abebe Admin",
    email: "abebe@etgcompany.et",
    role: "admin",
    active: true,
  },
  {
    id: "2",
    username: "manager",
    password: "manager123",
    name: "Kebede Manager",
    email: "kebede@etgcompany.et",
    role: "manager",
    active: true,
  },
  {
    id: "3",
    username: "sales",
    password: "sales123",
    name: "Mulu Sales",
    email: "mulu@etgcompany.et",
    role: "sales",
    active: true,
  },
  {
    id: "4",
    username: "procurement",
    password: "procurement123",
    name: "Tekle Procurement",
    email: "tekle@etgcompany.et",
    role: "procurement",
    active: true,
  },
  {
    id: "5",
    username: "warehouse",
    password: "warehouse123",
    name: "Berhanu Warehouse",
    email: "berhanu@etgcompany.et",
    role: "warehouse",
    active: true,
  },
  {
    id: "6",
    username: "finance",
    password: "finance123",
    name: "Aster Finance",
    email: "aster@etgcompany.et",
    role: "finance",
    active: true,
  },
]

export const mockCustomers: Customer[] = [
  {
    id: "C001",
    name: "Seattle Coffee Importers LLC",
    email: "orders@seattlecoffee.com",
    phone: "+1-206-555-0101",
    country: "USA",
    creditLimit: 100000,
    createdAt: "2024-01-15",
  },
  {
    id: "C002",
    name: "London Coffee Traders Ltd",
    email: "purchasing@londoncoffee.co.uk",
    phone: "+44-20-7123-4567",
    country: "United Kingdom",
    creditLimit: 150000,
    createdAt: "2024-02-20",
  },
  {
    id: "C003",
    name: "Tokyo Specialty Coffee Co.",
    email: "buying@tokyocoffee.jp",
    phone: "+81-3-4567-8901",
    country: "Japan",
    creditLimit: 120000,
    createdAt: "2024-03-10",
  },
  {
    id: "C004",
    name: "Sydney Coffee Distributors Pty Ltd",
    email: "procurement@sydneycoffee.com.au",
    phone: "+61-2-9876-5432",
    country: "Australia",
    creditLimit: 80000,
    createdAt: "2024-04-05",
  },
]

export const mockProducts: Product[] = [
  {
    id: "P001",
    code: "COF-YIR-001",
    name: "Yirgacheffe Grade 1 Coffee Beans (60kg Bag)",
    category: "Coffee Green Beans",
    unit: "Bag",
    costPrice: 1200,
    salePrice: 2200,
    currentStock: 250,
    reorderLevel: 50,
  },
  {
    id: "P002",
    code: "COF-SID-001",
    name: "Sidamo Grade 2 Coffee Beans (60kg Bag)",
    category: "Coffee Green Beans",
    unit: "Bag",
    costPrice: 950,
    salePrice: 1800,
    currentStock: 180,
    reorderLevel: 40,
  },
  {
    id: "P003",
    code: "COF-HAR-001",
    name: "Harrar Grade 3 Coffee Beans (60kg Bag)",
    category: "Coffee Green Beans",
    unit: "Bag",
    costPrice: 800,
    salePrice: 1500,
    currentStock: 150,
    reorderLevel: 30,
  },
  {
    id: "P004",
    code: "COF-DEC-001",
    name: "Decaf Ethiopian Coffee Beans (60kg Bag)",
    category: "Coffee Green Beans",
    unit: "Bag",
    costPrice: 1500,
    salePrice: 2800,
    currentStock: 80,
    reorderLevel: 20,
  },
  {
    id: "P005",
    code: "COF-GRO-001",
    name: "Organic Ethiopian Coffee Blend (60kg Bag)",
    category: "Coffee Green Beans",
    unit: "Bag",
    costPrice: 1800,
    salePrice: 3200,
    currentStock: 60,
    reorderLevel: 15,
  },
  {
    id: "P006",
    code: "COF-ROA-001",
    name: "Medium Roast Ethiopian Coffee (250g Pack)",
    category: "Roasted Coffee",
    unit: "Pack",
    costPrice: 80,
    salePrice: 150,
    currentStock: 500,
    reorderLevel: 100,
  },
  {
    id: "P007",
    code: "COF-ROA-002",
    name: "Dark Roast Ethiopian Coffee (250g Pack)",
    category: "Roasted Coffee",
    unit: "Pack",
    costPrice: 80,
    salePrice: 150,
    currentStock: 450,
    reorderLevel: 100,
  },
  {
    id: "P008",
    code: "COF-CUP-001",
    name: "Ethiopian Coffee Cups (Pack of 50)",
    category: "Coffee Accessories",
    unit: "Pack",
    costPrice: 200,
    salePrice: 400,
    currentStock: 200,
    reorderLevel: 50,
  },
]

export const mockSuppliers: Supplier[] = [
  {
    id: "S001",
    name: "Yirgacheffe Coffee Farmers Cooperative Union",
    email: "info@ycfcu.et",
    phone: "+251-47-111-1111",
    country: "Ethiopia",
    paymentTerms: "Net 30",
    createdAt: "2023-06-15",
  },
  {
    id: "S002",
    name: "Sidama Coffee Farmers Union",
    email: "orders@sidamacoffee.et",
    phone: "+251-46-222-2222",
    country: "Ethiopia",
    paymentTerms: "Net 45",
    createdAt: "2023-07-20",
  },
  {
    id: "S003",
    name: "Harrar Coffee Estate",
    email: "sales@harrarcoffee.et",
    phone: "+251-33-333-3333",
    country: "Ethiopia",
    paymentTerms: "Net 30",
    createdAt: "2023-08-10",
  },
  {
    id: "S004",
    name: "Oromia Coffee Processing Plant",
    email: "procurement@oromiacoffee.et",
    phone: "+251-11-444-4444",
    country: "Ethiopia",
    paymentTerms: "Net 60",
    createdAt: "2023-09-05",
  },
]

export const mockSalesOrders: SalesOrder[] = [
  {
    id: "SO001",
    orderNumber: "SO-2024-001",
    customerId: "C001",
    customerName: "Seattle Coffee Importers LLC",
    orderDate: "2024-11-01",
    deliveryDate: "2024-11-15",
    status: "completed",
    items: [
      {
        productId: "P001",
        productName: "Yirgacheffe Grade 1 Coffee Beans (60kg Bag)",
        quantity: 50,
        unitPrice: 2200,
        costPrice: 1200,
        total: 110000,
      },
      {
        productId: "P006",
        productName: "Medium Roast Ethiopian Coffee (250g Pack)",
        quantity: 200,
        unitPrice: 150,
        costPrice: 80,
        total: 30000,
      },
    ],
    subtotal: 140000,
    tax: 14000,
    total: 154000,
    profit: 50000,
    createdBy: "Mulu Sales",
  },
  {
    id: "SO002",
    orderNumber: "SO-2024-002",
    customerId: "C002",
    customerName: "London Coffee Traders Ltd",
    orderDate: "2024-11-05",
    deliveryDate: "2024-11-20",
    status: "shipped",
    items: [
      {
        productId: "P002",
        productName: "Sidamo Grade 2 Coffee Beans (60kg Bag)",
        quantity: 75,
        unitPrice: 1800,
        costPrice: 950,
        total: 135000,
      },
      {
        productId: "P007",
        productName: "Dark Roast Ethiopian Coffee (250g Pack)",
        quantity: 150,
        unitPrice: 150,
        costPrice: 80,
        total: 22500,
      },
    ],
    subtotal: 157500,
    tax: 15750,
    total: 173250,
    profit: 65000,
    createdBy: "Mulu Sales",
  },
  {
    id: "SO003",
    orderNumber: "SO-2024-003",
    customerId: "C003",
    customerName: "Tokyo Specialty Coffee Co.",
    orderDate: "2024-12-01",
    deliveryDate: "2024-12-15",
    status: "approved",
    items: [
      {
        productId: "P003",
        productName: "Harrar Grade 3 Coffee Beans (60kg Bag)",
        quantity: 40,
        unitPrice: 1500,
        costPrice: 800,
        total: 60000,
      },
      {
        productId: "P004",
        productName: "Decaf Ethiopian Coffee Beans (60kg Bag)",
        quantity: 20,
        unitPrice: 2800,
        costPrice: 1500,
        total: 56000,
      },
      {
        productId: "P008",
        productName: "Ethiopian Coffee Cups (Pack of 50)",
        quantity: 30,
        unitPrice: 400,
        costPrice: 200,
        total: 12000,
      },
    ],
    subtotal: 128000,
    tax: 12800,
    total: 140800,
    profit: 48000,
    createdBy: "Mulu Sales",
  },
  {
    id: "SO004",
    orderNumber: "SO-2024-004",
    customerId: "C004",
    customerName: "Sydney Coffee Distributors Pty Ltd",
    orderDate: "2024-12-10",
    deliveryDate: "2024-12-25",
    status: "draft",
    items: [
      {
        productId: "P005",
        productName: "Organic Ethiopian Coffee Blend (60kg Bag)",
        quantity: 25,
        unitPrice: 3200,
        costPrice: 1800,
        total: 80000,
      },
    ],
    subtotal: 80000,
    tax: 8000,
    total: 88000,
    profit: 35000,
    createdBy: "Mulu Sales",
  },
]

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: "PO001",
    poNumber: "PO-2024-001",
    supplierId: "S001",
    supplierName: "Yirgacheffe Coffee Farmers Cooperative Union",
    orderDate: "2024-10-15",
    expectedDate: "2024-11-15",
    status: "completed",
    items: [
      {
        productId: "P001",
        productName: "Yirgacheffe Grade 1 Coffee Beans (60kg Bag)",
        quantity: 300,
        unitPrice: 1200,
        total: 360000,
      },
    ],
    total: 360000,
    createdBy: "Tekle Procurement",
  },
  {
    id: "PO002",
    poNumber: "PO-2024-002",
    supplierId: "S002",
    supplierName: "Sidama Coffee Farmers Union",
    orderDate: "2024-11-01",
    expectedDate: "2024-12-01",
    status: "received",
    items: [
      {
        productId: "P002",
        productName: "Sidamo Grade 2 Coffee Beans (60kg Bag)",
        quantity: 250,
        unitPrice: 950,
        total: 237500,
      },
    ],
    total: 237500,
    createdBy: "Tekle Procurement",
  },
  {
    id: "PO003",
    poNumber: "PO-2024-003",
    supplierId: "S003",
    supplierName: "Harrar Coffee Estate",
    orderDate: "2024-12-01",
    expectedDate: "2024-12-20",
    status: "ordered",
    items: [
      {
        productId: "P003",
        productName: "Harrar Grade 3 Coffee Beans (60kg Bag)",
        quantity: 200,
        unitPrice: 800,
        total: 160000,
      },
      {
        productId: "P004",
        productName: "Decaf Ethiopian Coffee Beans (60kg Bag)",
        quantity: 100,
        unitPrice: 1500,
        total: 150000,
      },
    ],
    total: 310000,
    createdBy: "Tekle Procurement",
  },
  {
    id: "PO004",
    poNumber: "PO-2024-004",
    supplierId: "S004",
    supplierName: "Oromia Coffee Processing Plant",
    orderDate: "2024-12-10",
    expectedDate: "2025-01-10",
    status: "draft",
    items: [
      {
        productId: "P005",
        productName: "Organic Ethiopian Coffee Blend (60kg Bag)",
        quantity: 150,
        unitPrice: 1800,
        total: 270000,
      },
      {
        productId: "P006",
        productName: "Medium Roast Ethiopian Coffee (250g Pack)",
        quantity: 1000,
        unitPrice: 80,
        total: 80000,
      },
    ],
    total: 350000,
    createdBy: "Tekle Procurement",
  },
]

export const mockWarehouses: Warehouse[] = [
  {
    id: "W001",
    name: "Addis Ababa Main Warehouse",
    location: "Bole Industrial Area",
    capacity: 10000,
  },
  {
    id: "W002",
    name: "Djibouti Port Hub",
    location: "Djibouti Port",
    capacity: 5000,
  },
]
